export const actionType = {
    
    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',

    UPDATE_ORDER_REQUEST: 'UPDATE_ORDER_REQUEST',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_FAILED: 'UPDATE_ORDER_FAILED',

    DELETE_ORDER_REQUEST: 'DELETE_ORDER_REQUEST',
    DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
    DELETE_ORDER_FAILED: 'DELETE_ORDER_FAILED',

    ALL_ORDER_REQUEST: 'ALL_ORDER_REQUEST',
    ALL_ORDER_SUCCESS: 'ALL_ORDER_SUCCESS',
    ALL_ORDER_FAILED: 'ALL_ORDER_FAILED',

    SINGLE_ORDER_REQUEST: 'SINGLE_ORDER_REQUEST',
    SINGLE_ORDER_SUCCESS: 'SINGLE_ORDER_SUCCESS',
    SINGLE_ORDER_FAILED: 'SINGLE_ORDER_FAILED',

    ORDER_RESET: 'ORDER_RESET'
    
}