export const actionType = {
    
    SUB_REQUEST: 'SUB_REQUEST',
    SUB_SUCCESS: 'SUB_SUCCESS',
    SUB_FAILED: 'SUB_FAILED',

    SUB_DETAIL_REQUEST: 'SUB_DETAIL_REQUEST',
    SUB_DETAIL_SUCCESS: 'SUB_DETAIL_SUCCESS',
    SUB_DETAIL_FAILED: 'SUB_DETAIL_FAILED',
    
    SUB_CREATE_REQUEST: 'SUB_CREATE_REQUEST',
    SUB_CREATE_SUCCESS: 'SUB_CREATE_SUCCESS',
    SUB_CREATE_FAILED: 'SUB_CREATE_FAILED',

    SUB_UPDATE_REQUEST: 'SUB_UPDATE_REQUEST',
    SUB_UPDATE_SUCCESS: 'SUB_UPDATE_SUCCESS',
    SUB_UPDATE_FAILED: 'SUB_UPDATE_FAILED',

    SUB_DELETE_REQUEST: 'SUB_DELETE_REQUEST',
    SUB_DELETE_SUCCESS: 'SUB_DELETE_SUCCESS',
    SUB_DELETE_FAILED: 'SUB_DELETE_FAILED',

}