export const actionType = {
    
    CATEGORY_REQUEST: 'CATEGORY_REQUEST',
    CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
    CATEGORY_FAILED: 'CATEGORY_FAILED',

    CATEGORY_DETAIL_REQUEST: 'CATEGORY_DETAIL_REQUEST',
    CATEGORY_DETAIL_SUCCESS: 'CATEGORY_DETAIL_SUCCESS',
    CATEGORY_DETAIL_FAILED: 'CATEGORY_DETAIL_FAILED',
    
    CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
    CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
    CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',

    CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
    CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
    CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',

    CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
    CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
    CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',
    
    CATEGORY_RESET: 'CATEGORY_RESET'
}