export const actionType = {

    SEARCH_PRODUCT_REQUEST: 'SEARCH_PRODUCT_REQUEST',
    SEARCH_PRODUCT_SUCCESS: 'SEARCH_PRODUCT_SUCCESS',
    SEARCH_PRODUCT_FAILED: 'SEARCH_PRODUCT_FAILED',

    SEARCH_TEXT: 'SEARCH_TEXT',

}