export const actionType = {
    ADD_TO_WISHLIST_REQUEST: 'ADD_TO_WISHLIST_REQUEST',
    ADD_TO_WISHLIST_SUCCESS: 'ADD_TO_WISHLIST_SUCCESS',
    ADD_TO_WISHLIST_FAILED: 'ADD_TO_WISHLIST_FAILED',

    REMOVE_TO_WISHLIST_REQUEST: 'REMOVE_TO_WISHLIST_REQUEST',
    REMOVE_TO_WISHLIST_SUCCESS: 'REMOVE_TO_WISHLIST_SUCCESS',
    REMOVE_TO_WISHLIST_FAILED: 'REMOVE_TO_WISHLIST_FAILED',

    WISHLIST_REQUEST: 'WISHLIST_REQUEST',
    WISHLIST_SUCCESS: 'WISHLIST_SUCCESS',
    WISHLIST_FAILED: 'WISHLIST_FAILED',

}