export const actionType = {
    
    PRODUCT_REQUEST: 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_FAILED: 'PRODUCT_FAILED',

    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILED: 'PRODUCT_DETAIL_FAILED',

    PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_FAILED: 'PRODUCT_CREATE_FAILED',

    PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',

    PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAILED: 'PRODUCT_DELETE_FAILED',

    PRODUCT_RESET: 'PRODUCT_RESET',
    PRODUCT_RESET_SUCCESS: 'PRODUCT_RESET_SUCCESS',
    PRODUCT_RESET_FAILED: 'PRODUCT_RESET_FAILED',


    PRODUCT_BELONG_TO_SPECIFIC_CATEGORY_REQUEST: 'PRODUCT_BELONG_TO_SPECIFIC_CATEGORY_REQUEST',
    PRODUCT_BELONG_TO_SPECIFIC_CATEGORY_SUCCESS: 'PRODUCT_BELONG_TO_SPECIFIC_CATEGORY_SUCCESS',
    PRODUCT_BELONG_TO_SPECIFIC_CATEGORY_FAILED: 'PRODUCT_BELONG_TO_SPECIFIC_CATEGORY_FAILED',

    PRODUCT_BELONG_TO_SPECIFIC_SUB_CATEGORY_REQUEST: 'PRODUCT_BELONG_TO_SPECIFIC_SUB_CATEGORY_REQUEST',
    PRODUCT_BELONG_TO_SPECIFIC_SUB_CATEGORY_SUCCESS: 'PRODUCT_BELONG_TO_SPECIFIC_SUB_CATEGORY_SUCCESS',
    PRODUCT_BELONG_TO_SPECIFIC_SUB_CATEGORY_FAILED: 'PRODUCT_BELONG_TO_SPECIFIC_SUB_CATEGORY_FAILED',


    BEST_PRODUCT_REQUEST: 'BEST_PRODUCT_REQUEST',
    BEST_PRODUCT_SUCCESS: 'BEST_PRODUCT_SUCCESS',
    BEST_PRODUCT_FAILED: 'BEST_PRODUCT_FAILED',

    NEW_ARRIVAL_PRODUCT_REQUEST: 'NEW_ARRIVAL_PRODUCT_REQUEST',
    NEW_ARRIVAL_PRODUCT_SUCCESS: 'NEW_ARRIVAL_PRODUCT_SUCCESS',
    NEW_ARRIVAL_PRODUCT_FAILED: 'NEW_ARRIVAL_PRODUCT_FAILED',
    
}