export const actionType = {
    CREATE_COUPON_REQUEST: 'CREATE_COUPON_REQUEST',
    CREATE_COUPON_SUCCESS: 'CREATE_COUPON_SUCCESS',
    CREATE_COUPON_FAILED: 'CREATE_COUPON_FAILED',
    
    GET_COUPON_REQUEST: 'GET_COUPON_REQUEST',
    GET_COUPON_SUCCESS: 'GET_COUPON_SUCCESS',
    GET_COUPON_FAILED: 'GET_COUPON_FAILED',

    DELETE_COUPON_REQUEST: 'DELETE_COUPON_REQUEST',
    DELETE_COUPON_SUCCESS: 'DELETE_COUPON_SUCCESS',
    DELETE_COUPON_FAILED: 'DELETE_COUPON_FAILED',
    
    APPLY_COUPON_REQUEST: 'APPLY_COUPON_REQUEST',
    APPLY_COUPON_SUCCESS: 'APPLY_COUPON_SUCCESS',
    APPLY_COUPON_FAILED: 'APPLY_COUPON_FAILED',
    
    
}