export const actionType = {
    
    USER_TRACK_REQUEST: 'USER_TRACK_REQUEST',
    USER_TRACK_SUCCESS: 'USER_TRACK_SUCCESS',
    USER_TRACK_FAILED: 'USER_TRACK_FAILED',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

    USER_LOGIN_WITH_GOOGLE_REQUEST: 'USER_LOGIN_WITH_GOOGLE_REQUEST',
    USER_LOGIN_WITH_GOOGLE_SUCCESS: 'USER_LOGIN_WITH_GOOGLE_SUCCESS',
    USER_LOGIN_WITH_GOOGLE_FAILED: 'USER_LOGIN_WITH_GOOGLE_FAILED',

    
    USER_LOGOUT: 'USER_LOGOUT',
    
    
    SAVE_ADDRESS_REQUEST: 'SAVE_ADDRESS_REQUEST',
    SAVE_ADDRESS_SUCCESS: 'SAVE_ADDRESS_SUCCESS',
    SAVE_ADDRESS_FAILED: 'SAVE_ADDRESS_FAILED',
}